### ISSUE TITLE
Ошибка инсталяции

### ISSUE THREAD

**Issue by stilet** [yandex-money/yandex-money-cms-prestashop#11]
Prestashop 1.6.0.14
При инсталяции модуля (скачанного с github) пишет, что "action.php is not a valid module name."
Инсталяция не проходит.

**Comment by lead-worker** [comment]
PrestaShop 1.6.0.14 
Налогичная ситуация - "action.php is not a valid module name"

![2015-06-29 15-54-04 mozilla firefox](https://cloud.githubusercontent.com/assets/9391382/8408260/2d463878-1e77-11e5-95e0-e4878e815d9a.png)

**Comment by lead-worker** [comment]
Распаковал архив. Изменил названия файлов:
action.php  ->  _action.php
actions.php -> _actions.php
callback.php -> _callback.php
После этого запаковал в .zip
Теперь загрузка модуля проходит успешно.
После загрузки, вернул назад названия файлов и произвел установку через CMS. Установка прошла успешно. Работоспосбность модуля тестирую.

**Comment by ikarmanov** [comment]
Добрый день.

Мы выпустили новую версию модуля. Ваша проблема еще актуальна?
