### ISSUE TITLE
Счетчик недоступен

### ISSUE THREAD

**Issue by igor3dviz** [yandex-money/yandex-money-cms-prestashop#14]
Здравствуйте.
После успешной настройки метрики, почему-то код счетчика на странице счетчиков недоступен. Что мне с этим можно сделать?

**Comment by ikarmanov** [comment]
Добрый день, igor3dviz.

По вопросам доступа к коду счетчиков на страницах сервиса Яндекс.Метрика необходимо обратиться в его службу поддержки (см. [форму обратной связи](http://feedback2.yandex.ru/metrika/-/)).
