### ISSUE TITLE
Способ оплаты

### ISSUE THREAD

**Issue by igor3dviz** [yandex-money/yandex-money-cms-prestashop#15]
В письме, присылаемое пользователям после оплаты, способом оплаты пишется "Y.CMS Prestashop", что очень плохо. Лично меня все это бы смутило, т.к. уровень доверят к непонятным названиям всегда ниже. Большущая просьба исправить на соответствующий способ оплаты. Я так понимаю, в коде оно без альтернативно, но хотелось бы видеть в письме, к примеру, "оплата картой", если пользователь выбирает карту, и "оплата webmoney", если пользователь выбирает его. 
Спасибо

**Comment by ikarmanov** [comment]
Спасибо за замечание. Добавили в список планируемых изменений.

**Comment by KPG1** [comment]
Для администратора тоже было бы удобно видеть выбранный способ оплаты.
