### ISSUE TITLE
Yandex.Kassa (метод формирования заказа)

### ISSUE THREAD

**Issue by Davin4i90** [yandex-money/yandex-money-cms-prestashop#16]
Обслуживаю 2 магазина с установленным модулем.
Бизнес-процессы разные. 

Одним удобно, чтобы заказ формировался в магазине до поступления сведений от кассы о результате попытки оплаты, и когда сведения поступают - меняется статус на нужный. 

Вторым, так как они торгуют онлайн-контентом, категорично необходимо, чтобы заказ создавался только после поступлений сведений об оплате от сервера кассы. 

На данный момент если клиент вернулся в магазин во время оплаты - корзина пуста, повторить оплату сформированного заказа невозможно! Хотелось бы, чтобы отказавшись от платежа и вернувшись в магазин клиент мог увидеть полную корзину.

Предлагаю осуществить возможность выбора способа создания заказа в магазине - ДО или ПОСЛЕ поступления информации об оплате от сервера кассы.

**Comment by ikarmanov** [comment]
Добрый день.

Спасибо. Мы рассмотрим Ваше предложение.
