### ISSUE TITLE
Upgrade v1.1.1

### ISSUE THREAD

**Issue by KPG1** [yandex-money/yandex-money-cms-prestashop#19]
Добрый день!
Prestashop 1.6.1.4 
Как корректно обновиться с версии модуля 1.1.1 ?
Попробовал обновить, настройки все сохранились, кроме ссылок payment_kassa
Ссылки надо править в личном кабинете яндекс кассы (т.е. писать в поддержку)?

Добавились новые способы оплаты. Все активировал.
Попробовал протестировать и получил техническую ошибку на сайте яндекс, кнопка вернуться в магазин не срабатывает (ссылка ведет на .../module/yamodule/fail?orderNumber=KASSA...), сервер магазина выдает ошибку 500 при возврате по этой ссылке

Заказ не формируется, товары остаются в корзине.

**Comment by ikarmanov** [comment]
Добрый день.

> Ссылки надо править в личном кабинете яндекс кассы (т.е. писать в поддержку)?
Да, так как адрес немного изменился.

Вам необходимо удалить старую версию модуля и установить новую. Если во время платежа возникает ошибка (на стороне сервиса Яндекс.Касса), то Вам необходимо обратиться к техническим специалистам сервиса по контактам на [странице](https://kassa.yandex.ru/contacts)
