### ISSUE TITLE
Из-за модуля не работает модуль анимации v1.3.6.1

### ISSUE THREAD

**Issue by brusdevelopement** [yandex-money/yandex-money-cms-prestashop#21]
На главной странице установлен модуль анимации revolution slider. Включил модуль яндекса, настроил и подключил метрику. После этого анимация перестала работать. Захожу в админку, выключаю модуль яндекса, анимация снова работает. Сегодня буду искать причины. Очень жаль, что так получилось. Модуль очень хороший.

**Comment by brusdevelopement** [comment]
Обнаружил где ошибка, но в чем конкретно она, пока не разобрался.

во всем виноват файл: /modules/yamodule/views/js/front.js

глючит кусок кода с 35 по 55 строку:

`if(celi_cart)
	{
		var old_addCart = ajaxCart.add;
		ajaxCart.add = function (idProduct, idCombination, addedFromProductPage, callerElement, quantity, wishlist)
		{
			old_addCart(idProduct, idCombination, addedFromProductPage, callerElement, quantity, wishlist);
			$.ajax({
				type: 'POST',
				url: baseDir + 'modules/yamodule/action.php?rand=' + new Date().getTime(),
				headers: { "cache-control": "no-cache" },
				async: true,
				cache: false,
				dataType : "json",
				data: 'action=add_cart&id_product=' + idProduct + '&quantity=' + quantity + '&token=' + static_token + '&id_product_attribute=' + idCombination,
				success: function(data)
				{
					metrikaReach('metrikaCart', data.params);
				}
			});
		}
	}`

Если его закомментировать, анимация на сайте работает.

**Comment by brusdevelopement** [comment]
Можете подсказать, в чем может быть проблема?

**Comment by brusdevelopement** [comment]
Нашел причину. Мой сайт находился в режиме каталога, поэтому корзина была отключена. С отключенной корзиной скрипт крашит модуль анимации. Пока не знаю почему, но причина точно в корзине. После перевода магазина в рабочий режим, всё работает отлично.

**Comment by brusdevelopement** [comment]
Нашел причину. Ты в скрипте не делаешь проверку на режим каталога.

Сделай проверку PS_CATALOG_MODE

Я поправил у себя так. Внес изменения в файл /modules/yamodule/yamodule.php

строка 810: было
`if (Configuration::get('YA_METRIKA_CELI_CART')) {`

стало:

`if (Configuration::get('YA_METRIKA_CELI_CART') && !Configuration::get('PS_CATALOG_MODE')) {`

Таким образом всё будет прекрасно работать и в режиме каталога и без него.

**Comment by ikarmanov** [comment]
Добрый день.

Спасибо за информацию. Проверим её актуальность на версии 1.3.8 и включим изменения в 1.4.0.
