### ISSUE TITLE
Оплата после подверждения

### ISSUE THREAD

**Issue by mr-slonn** [yandex-money/yandex-money-cms-prestashop#22]
Многие магазины обрабатывают заказ после проверки, к примеру наличия на складе/поставщиков, уточнений с клиентами различных моментов (цвет, размер, доставка и т.д)

Поэтому хотелось бы что бы в модуле присутствовал следующий функционал:
при оформлении корзины клиент выбирает что будет оплачивать картой (ну или другими сервисами я.кассы), корзина становится заказом со статусом к примру "На подтверждении менеджером". Если всё в порядке менеджер меняет статус заказа на "В ожидании оплаты" и у клиента в личном кабинете в разделе "Мои заказы" в детальном описании заказа появляется уже возможность оплатить заказ я.кассой.

**Comment by ikarmanov** [comment]
Добрый день.

Спасибо за предложение. Мы подумаем над этим.
