### ISSUE TITLE
Ошибка при оплате

### ISSUE THREAD

**Issue by artem78** [yandex-money/yandex-money-cms-prestashop#23]
При оплате картой возникает ошибка: Not received the correct data from Yandex.Money

**Comment by ikarmanov** [comment]
Добрый день.

Опишите Вашу ситуацию подробней. В каком режиме (Яндекс.Касса или Яндекс.Деньги) работает модуль? На какой странице отображается ошибка? Настройка модуля выполнена по [инструкции](https://kassa.yandex.ru/files/manual_y.cms_prestashop.pdf)?

**Comment by artem78** [comment]
Работает в режиме Яндекс.Деньги. При оплате возникает следующая ошибка:
```
Ошибка
Этому приложению отказано в доступе.
Свяжитесь с его разработчиком и укажите сведения об ошибке (invalid_request).
```

Ставил по вашей инструкции. Здесь создал приложение - https://money.yandex.ru/myservices/new.xml и занёс id приложения с секретным ключом в настройки модуля.

**Comment by ostulov** [comment]
Проверьте, что платеж выполняется не из под учетной записи, на которую настроен прем оплаты. Перевести деньги самому себе нельзя, это будет приводить к подобной ошибке.

Если проблема продолжает возникать, рекомендую написать нам на почту cms@yamoney.ru с подробным описанием проблемы.
