### ISSUE TITLE
1.3.7 version - Metrika logic error!!!

### ISSUE THREAD

**Issue by brusdevelopement** [yandex-money/yandex-money-cms-prestashop#24]
Installed module on Prestashop 1.6.1.6
Made Metrika settings: METRIKA_NUMBER, METRIKA_ID_APPLICATION, METRIKA_PASSWORD_APPLICATION
After Saving results I got an error: "Saving the settings the meter is not the meter number is incorrect."

go in /modules/yamodule/yamodule.php
line 1276:
`if (Configuration::get('YA_METRIKA_TOKEN') != '') {
            if ($response) {
                $counter = $m->getCounter();
                if (!empty($counter->counter->code)) {
                    Configuration::UpdateValue('YA_METRIKA_CODE', $counter->counter->code, true);
                }
                $otvet = $m->editCounter();
                if ($otvet->counter->id != Configuration::get('YA_METRIKA_NUMBER')) {
                    $error .= $this->displayError($this->l('Saving the settings the meter is not the meter number is incorrect.'));
                }`

Opened my SQL:
in table ps_configuration there is NO field YA_METRIKA_CODE

After a while I tried to play with logic and changedthe line from
`if (!empty($counter->counter->code)) {
                    Configuration::UpdateValue('YA_METRIKA_CODE', $counter->counter->code, true);
                }`
to
`if (empty($counter->counter->code)) {
                    Configuration::UpdateValue('YA_METRIKA_CODE', $counter->counter->code, true);
                }`
So it worked and the code generated a field YA_METRIKA_CODE in a table.

Look at your logic one more. Try to change the AUTH parameters and generate a new token. Something is wrong with the logic.

P.S. Я конечно завел твой модуль у себя, но только с толкача. Через mysql и редактирование php, но точно там с логикой ошибка где-то. Код метрики не генерится самостоятельно почему-то.

**Comment by ikarmanov** [comment]
Hi.

Thank you for mistake description. We will check it.
