### ISSUE TITLE
Ошибка инсталляции

### ISSUE THREAD

**Issue by brusdevelopement** [yandex-money/yandex-money-cms-prestashop#25]
Штука такая. Если в PrestaShop добавлено обязательное поле ОТЧЕСТВО для всех новых клиентов (middlename), то при установке код валиться с ошибкой. Всё из-за того, что отчество стоит обязательным полем при регистрации нового юзера (ведь теперь при почтовой отправке отчество обязательно в РФ). Таким образом приходиться до установки руками править yamodule.php и добавлять после $customer->lastname = 'YA POKUPKI Not Delete'; строку $customer->middlename = 'YA POKUPKI Not Delete';

Тогда конечно всё гладко устанавливается. Но без навыков программирования получается модуль не поставить))) Ну или если этот пост не прочесть заранее)) Думаю можно добавить логику туда, проверки есть еще обязательные поля или нет при регистрации. У всех магазинов в РФ я думаю отчество доработано. Иначе не представляю как они работают.

**Comment by ikarmanov** [comment]
Добрый день.

Спасибо за информацию. Изменения включим в новую версию модуля.
