### ISSUE TITLE
Отсутствуют обязательные поля...

### ISSUE THREAD

**Issue by Pavel060907** [yandex-money/yandex-money-cms-prestashop#26]
Здравствуйте!

При проверке прайса появляется такой результат:

Элемент sales_notes присутствуют у 0% товарных предложений
Используйте элемент <sales_notes>, чтобы указать:
минимальную сумму заказа (обязательно);
минимальную партию товара (обязательно);
необходимость предоплаты (обязательно);
варианты оплаты (необязательно);
условия акции (необязательно).
Содержание элемента должно соответствовать требованиям к рекламным материалам, размещаемым на Маркете.

Это я что-то не указал или в модуле необходимы какие-либо настройки?

**Comment by ikarmanov** [comment]
Добрый день.

В модуле параметр sales_notes создается для товаров с ограничением на минимальное кол-во в заказе. Специальных настроек не требуется.
