### ISSUE TITLE
Одни баги

### ISSUE THREAD

**Issue by indigoshop** [yandex-money/yandex-money-cms-prestashop#28]
Второй раз на одни и те же грабли. В прошлом году пытались установить модуль , поломался весь сайт. В этом году та же история. После установки модуля на сайте тут же поломалось- навигация, отзывы, карусели товаров и брендов, чпу, корзина. Причём удаление модуля не решает проблемы, они остаются. В прошлом году пришлось делать бекап. Сегодня уже три часа пытаемся понять в чем проблема но пока безуспешно. Причём при удалении модуля на мобильной версии все вернулось в нормальное русло, все работает. А в полной версии проблемы остаются.

**Comment by ostulov** [comment]
Мы постоянно занимаемся улучшением модуля и помогаем решать проблемы. Если у вас возникают проблемы при использовании модуля, для оперативной поддержки просьба писать на почту cms@yamoney.ru с указанием подробностей.
