### ISSUE TITLE
Не работает метрика.

### ISSUE THREAD

**Issue by khokhlovalexander** [yandex-money/yandex-money-cms-prestashop#31]
Не отображается на странице кусок кода счетчика :

<noscript><div><img src="https://mc.yandex.ru/watch/ххххххх" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

пришлось вставлять его ручками.

**Comment by svobodamaks** [comment]
Обновите картинку, пожалуйста.

**Comment by ikarmanov** [comment]
Уже занимаемся
