### ISSUE TITLE
Prestashop 1.7 не поддерживается

### ISSUE THREAD

**Issue by Kariamba** [yandex-money/yandex-money-cms-prestashop#32]
При попытке развернуть модуль на prestashop 1.7 возвращает Fatal error:  Class 'Blowfish' not found.
Класса Rijndael тоже нет.

**Comment by svobodamaks** [comment]
"Для зрителей". Шаблон стандартный? 1.7 чистая установка? 
На версии 1.6.0.9 модуль не развернулся (хотя на чистом 1.6.1.10 проверили - работает), планируем апдейт и хотели сразу переехать на 1.7. Планируем еще тест на чистом 1.7, но хотелось бы услышать о вашем опыте.
Спасибо!

**Comment by Kariamba** [comment]
Да, стандартный шаблон.
Да, чистая установка v1.7.

Я бы пока повременил с переездом. У меня конечно не столь большой опыт - сейчас в поддержке 2 проекта на 1.6, и один на 1.4 (его как раз перетаскиваем на 1.7).

Мое сугубо личное мнение - 1.6 лучше, чем 1.7 (хотя в 1.7 есть свои приятные плюшки).

Мне не понравилось симфони в основе архитектуры. С точки зрения посетителей сайта может и прикольно, что они ни когда не увидят ошибок, но с точки зрения отладки - полный треш. На любую ошибку получаешь бактрейс из 15-20 позиций, и реально твоя ошибка находится где-то в середине этого трейса - остальное это обертки симфони.

В дев режиме ошибки выводятся там где они возникают - если в контенте, то все норм, а вот если в хуках где - то не всегда можно нормально прочесть лог. Поэтому настраивайте error.log для сайта в отдельный файл. Читайте ошибки через консольку: tail -20 error.log.

Если вдруг шаблон случайно сохраниться не в utf-8, то симфони упадет, но адекватной ошибки, почему он это сделал не выдаст (просто надо знать эту особенность и сразу проверять кодировку всех открытых файлов).

На локалке 1.7 развернули стандартным инсталлером, а на боевой уже дедовским способом переносили. Сразу после переноса на боевом симфони попыталась вывести какую-то ошибку (не знаю какую), но сервер умирал отжираж 480Мб оперативы и еще сверху просил порядка 508Мб... 1Гб на вывод ошибки - слишком круто, как по мне.

Ошибка в итоге оказалась в БД - дупликатед праймери кей. Почему-то при переносе БД, не перенеслись AI поля. Переносили через pma и sxd. В итоге нормально перенеслось только через консоль.

Еще одна особенность нашего проекта, что у заказчика корзина и чекайт ну совсем не совместимы с идеологией престы. Их у нас обрабатывают свои модули - обертки для стандартного функционала (тут удалось уйти от оверрайдов 1.4).

Но при тестах стандартного чекаута (чтобы проследить процесс оформления) у меня преста умирала при при последнем клике "оформить заказ". Я списал на вывод дампов (потом гитом их откатил), но первым делом проверьте чистое оформление заказа - возможно оно бажное и дело не в моих дампах.

Есть подозрение, что в $this->context огромная избыточность данных. Может это и стало причиной проблем памяти при выводе ошибки. print_r(payment_module) тоже умирает по оперативе ).

Ну и как всегда привет от документации (это по-моему беда всех версий престы).

Менюшка в ПА новая, местами не логичная и много переводов надо будет ручками делать. Система переводов осталась как и в 1.6, но теперь реализована гораздо лучше - сохраняется не все переводы, а по отдельно блокам (модулям, разделам и т.д). Теперь не надо в настройках сервера прописывать огромное кол-во полей для пост запросов.

А в целом 1.4 на 1.7 перенесли нормально (не через апдейтер конечно, а методом клонирования). Удалось избавиться от всех оверрайдов 1.4 - т.е. сейчас версия 1.7 у нас работает на чистых классах, контроллерах и модулях.

Для Яндекс.Кассы написали свой модуль (в анкете яндекса пришлось указывать "самописная CMS", чтобы можно было настраивать свои avisoURL и checkURL в ЛК).

Так что обязательно разворачивайте локалку, а еще лучше тестовый субдомен. И только после того как все обкатаете - переезжайте.

Надо понимать, что не любовь к симфони - это моя "субъективная не любовь". Я работал над 3 проектами на "чистом" симфони и еще двумя проектами построенными на базе (в том числе преста 1.7). И каждый раз она доставляла мне, хоть и не большую, но боль.

Посмотрим как дальше будет развиваться версия, возможно проекты с 1.6 со временем тоже начнем перекидывать на 1.7. Пилотный проект к тому же уже есть.

**Comment by esl51** [comment]
Начинаю проект на PrestaShop 1.7. Хотел использовать этот модуль, но он не встал по вышеописанной причине. Хотелось бы услышать комментарии разработчиков. Стоит ли ждать, или разрабатывать на 1.6?

**Comment by corsik** [comment]
На последней версии 1.7.2 тоже ошибки. Обращался в Яндекс, обещают поправить к октябрю!

**Comment by ikarmanov** [comment]
К октябрю планируем выпустить новую версию модуля.

**Comment by ivanscm** [comment]
@ikarmanov октябрь рядом ) ждем же

**Comment by corsik** [comment]
@ikarmanov подскажите, как успехи стоит ли ждать?

**Comment by ikarmanov** [comment]
Добрый день.

Новая версия модуля будет размещена на маркетплейсе Prestashop. Сейчас готовимся к публикации и немного корректируем инструкцию.

**Comment by corsik** [comment]
@ikarmanov он будет платный или бесплатный? Платные там и сейчас есть, думаю этот вопрос интересует многих.

**Comment by maratkh** [comment]
Слежу и очень жду такой же классный беспланый модуль 1.7.

**Comment by ikarmanov** [comment]
Добрый день.

Модуль точно будет бесплатным.

**Comment by ListWare** [comment]
Надеюсь ссылку на модуль в маркетплейсе вставите в описание... а то за маркетплейсом следить не так удобно, как за гитхабом

**Comment by ivanscm** [comment]
Задержка с релизом модуля, из-за релиза новой версии API Я.Кассы?

**Comment by MaiklSokolov** [comment]
Какие сроки по 1.7 модулю? Очень важно знать.

**Comment by MaiklSokolov** [comment]
и вот прошёл еще месяц(

**Comment by ikarmanov** [comment]
Добрый день.
Задержка вызвана тем, что опубликовать платный модуль в маркетплейсе CMS проще, чем бесплатный.

**Comment by MaiklSokolov** [comment]
1) ок
2) а можно  опубликовать на github?

**Comment by corsik** [comment]
@ikarmanov подскажите как успехи, когда ожидать?

**Comment by DaoKakao** [comment]
На 1.7 при попытке создать yml для яндекс-маркета вылетает exception при включенном gzip-сжатии.
А так вроде работает. Только алгоритм получения токена в админке как-то кривовато работат.

**Comment by corsik** [comment]
@ikarmanov подскажите, ну что виден конец в этом долгом пути? 
P.S.
За время пути собака могла подрасти! (Скоро уже выход 1.7.3)

**Comment by DaoKakao** [comment]
Бесполезно! Мне пришла ссылка на версию 2.0, скачал, поставил - там всё тоже довольно уныло. Судя по активности проекта - это совсем ни разу не приоритет для Яндекса.

**Comment by Listware** [comment]
@DaoKakao Ну почему же. Хоть как-то, но оно работает. Остальное потерпим

**Comment by Zeka13** [comment]
Очень ждём версию для 1.7, как бы не была хороша 1.6, надо двигаться вперёд!

**Comment by DaoKakao** [comment]
@Listware То-то и оно, что "работает" так, что ниакой разницы с "не работает". Например, мне в основном нужен экспорт в я.маркет. После установки модуля остальные сервисы я не настраивал. Тем не менее, почему-то перестал работать раздел "заказы", ругается как раз на y.cms 
Клёво работает, да?

**Comment by corsik** [comment]
Думаю тему можно считать закрытой, модуль уже появился https://github.com/yandex-money/yandex-money-ycms-v2-prestashop

**Comment by Zeka13** [comment]
закройте тогда тикет, а то вводит в заблуждение, наверное, есть смысл дать ссылку на новую версию в шапке README на этот модуль
