### ISSUE TITLE
Прошу реализовать метод repeatCardPayment

### ISSUE THREAD

**Issue by SobakaEbaka** [yandex-money/yandex-money-cms-prestashop#33]
Подробное описание нового метода 
https://tech.yandex.ru/money/doc/payment-solution/payment-management/payment-management-financial-repeat-card-payment-docpage/

**Comment by ikarmanov** [comment]
Спасибо. Рассмотрим ваше предложение. По срокам - в конце 2017 года будет понятно.

**Comment by ostulov** [comment]
Добавление метода repeatCardPayment производиться не будет.
