### ISSUE TITLE
Обновление и настройки

### ISSUE THREAD

**Issue by rusbolik** [yandex-money/yandex-money-cms-prestashop#35]
Здравствуйте.
Я обычный пользователь.
вопросы такие.
1. Как правильно обновить модуль чтобы не слетели все настройки уже сделанные?
2. Никак не могу понять откуда взять URL партнёрского API Яндекс.Маркет для вкладки     Заказы в Маркете
Помогите пожалуйста

Вопрос закрыт.

Но теперь вопрос другой. Самопроверка выдает 404 ошибку для yamodule/pokupki/cart 
как такое может быть?

**Comment by ikarmanov** [comment]
Мы исключили этот пункт из настроек, т.к. он статичен.
