### ISSUE TITLE
Yandex returns error page

### ISSUE THREAD

**Issue by klifer** [yandex-money/yandex-money-cms-prestashop#36]
Hey,

**(I write in eng. because of keyborad but I do understand russian, unswer can be in russian)**

Im trying your this plugin but unfortunately Yandex returns me error page :( I contacted Yandex support and they said: 

> Судя по логам, чек урл отвечает некорректно. Лог ниже:
> 
```2017-03-24T16:29:45.070 INFO [ipw1] [126533.SHID] [C7r9TGpCl6U=.243b] [206732a6-0009-5000-8000-00001eb94d29] [CommonHttp30Protocol] - paramsToSign: 'checkOrder;3200.00;10643;1003;126533;2000001125383;KASSA_8'
2017-03-24T16:29:45.070 INFO [ipw1] [126533.SHID] [C7r9TGpCl6U=.243b] [206732a6-0009-5000-8000-00001eb94d29] [CommonHTTPStub] - Request params:
orderNumber=KASSA_8
orderSumAmount=3200.00
cdd_exp_date=1120
shopArticleId=420795
cms_name=ya_prestashop
paymentPayerCode=4100322062290
cdd_rrn=479606410500
external_id=deposit
paymentType=AC
requestDatetime=2017-03-24T16:29:45.069+03:00
depositNumber=AmLiaRS8vaV-khH9aSWvo2jtgnAZ.001f.201703
nst_eplPayment=true
cdd_response_code=00
cps_user_country_code=PL
orderCreatedDatetime=2017-03-24T16:29:44.941+03:00
sk=y2ca755e41ec77a8a8982851dd97ee7a6
action=checkOrder
shopId=126533
scid=550459
shopSumBankPaycash=1003
shopSumCurrencyPaycash=10643
rebillingOn=false
orderSumBankPaycash=1003
cps_region_id=21417
orderSumCurrencyPaycash=10643
merchant_order_id=KASSA_8_240317162807_00000_126533
unilabel=206732a6-0009-5000-8000-00001eb94d29
cdd_pan_mask=444444|4448
label=KASSA_8
customerNumber=KASSA_8
yandexPaymentId=2570082242855
invoiceId=2000001125383
shopSumAmount=3088.00
md5=68EB68C9636E5515BB62AB486DF3FA98
 
 2017-03-24T16:29:45.510 INFO [ipw1] [126533.SHID] [C7r9TGpCl6U=.243b] [206732a6-0009-5000-8000-00001eb94d29] [CommonHTTPSCAConnector] - 439 ms for https://www.hereismydomainname.ru/?yandex_money=check
 2017-03-24T16:29:45.513 WARN [ipw1] [126533.SHID] [C7r9TGpCl6U=.243b] [206732a6-0009-5000-8000-00001eb94d29] [AbstractIPWPaymentHandler] - Сервер магазина не доступен: java.io.IOException: wrong response document
 (nested level more then 2). response: <!DOCTYPE HTML>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="ru-ru"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8 ie7" lang="ru-ru"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9 ie8" lang="ru-ru"><![endif]-->
<!-......
```

In the apache log file I have only one entry from Yandex:

`77.75.157.170 - - [25/Mar/2017:08:32:12 +0000] "POST /?yandex_money=check HTTP/1.1" 200 13222 "-" "Yandex.Money"`

Im using PrestaShop version: 1.6.1.11  and Y.CMS Prestashop v1.3.11 - by Яндекс.Деньги on the linux (Ubuntu / apache2 / php7 / mysql) platform.

Do you have any ideas what could be wrong? 

Thank you very much..

**Comment by ikarmanov** [comment]
Добрый день.

Для нашего модуля запросы от Яндекс.Кассы принимаются на другой адрес (указан в настройках модуля). В логах вижу отправку запроса на `/?yandex_money=check`. Рекомендую проверить настройки checkUrl/avisoUrl на стороне сервиса.

**Comment by klifer** [comment]
Яндекс ждет результатов тестирования. Они откроют услугу, когда результаты будут OK. Пока что ничего не могу поменять на панели Яндекса. Как подготовить модуль для тестового режима? Большое спасибо..

**Comment by klifer** [comment]
OK, Yandex wrote:

> Со своей стороны мы ожидаем полные адреса для запросов checkOrder и paymentAviso с указанием хоста и директории.

where my I find it in the plugin? how should settings looks like for standard configuration in Prestashop? Thx!

**Comment by ikarmanov** [comment]
Добрый день.

По умолчанию модуль обрабатывает запросы по адресу `https://<...>/module/yamodule/paymentkassa`. Этот адрес отображается в настройках модуля Y.CMS (вкладка Яндекс.Касса). Рекомендую сообщить менеджеру сервиса Яндекс.Касса новый адрес для запросов checkUrl/avisoUrl.

**Comment by klifer** [comment]
Thank you. Anyway it wasn't a problem. The problem was about password what can not to be (as you can find on the Yandex instruction) 'тестовый режим'. Yandex support changed it by Yandex site for '123' and I changed the configuration of the plugin. Then it started works. 

All is about poor information and documentation.
