### ISSUE TITLE
Баг в yamodule.php

### ISSUE THREAD

**Issue by brusdevelopement** [yandex-money/yandex-money-cms-prestashop#37]
Apache, nginx, php 5.6
Решил использовать модуль на новом проекте (на старом работает 3.1.4) После установки и настройки модуля код Метрики не появился. Проверил сначала mysql - там всё норм - значение METRICA_CODE появилось. Полез в код. Обнаружилась проблема в файле yamodule.php:

строка 799
```
if (!Configuration::get('YA_METRIKA_ACTIVE')) {
            $data .= 'var celi_order = false;';
            $data .= 'var celi_cart = false;';
            $data .= 'var celi_wishlist = false;';
            return '<p style="display:none;"><script type="text/javascript">'.$data.'</script></p>';
        }
```
и строка 824
```
if (Configuration::get('YA_METRIKA_CODE') != '') {
            return '<p style="display:none;"><script type="text/javascript">'.$data
            .'</script>'.Configuration::get('YA_METRIKA_CODE').'</p>';
        }
```
return не работает в обоих случаях. Быстро решил заменой return на echo. После этого код Метрики появился.

**Comment by ikarmanov** [comment]
Спасибо. Проверим ваше предложение

**Comment by ikarmanov** [comment]
Добрый день.

Это штатное поведение модуля, т.к. метрика вставляется в footer шаблона путём регистрации hook'a на вывод footer. Такая функция при вызове hook'a должна возвращать ссылку.
