### ISSUE TITLE
Yandex.Kassa не проходят оплаты

### ISSUE THREAD

**Issue by dimonius1993** [yandex-money/yandex-money-cms-prestashop#39]
Версия PrestaShop 1.6.0.11, венрсия модуля последняя. Проблема в следующем: например,  вид оплаты при оформлении заказа выбираю яндекс деньги, происходит редирект на яндекс деньги просит заплатить и т.д. НО в конце выдаёт "Что-то пошло не так". Это было на предыдущей версии модуля, на самой последней. Что самое интерессное модуль работал 2 месяца назад. Где-то читал, что у яндекса новые требования какие-то и модуль править "под них" нужно. Просьба помочь куда копать. Спасибо!

**Comment by ikarmanov** [comment]
Рекомендую по подобному кейсу обратиться в поддержку по адресу cms@yamoney.ru
