### ISSUE TITLE
ФЗ-54 Купон на бесплатную доставку дает ошибку

### ISSUE THREAD

**Issue by Sovush** [yandex-money/yandex-money-cms-prestashop#40]
Связка с кассой Атол онлайн. Преста 1.6.1.4 Если использовать при заказе купон на скидку- все нормально. Если купон на бесплатную доставку- оплата не проходит. Атол в логах пишет: error=SendReceiptToAtolError {code=-3813, text='Не удалось зарегистрировать скидку на документ в ККТ} Описание: Неверная величина скидки/надбавки // Модуль не передает значение скидки на доставку. Использование купонов, по которым доставка бесплатна- невозможно

**Comment by ostulov** [comment]
https://github.com/yandex-money/yandex-money-cms-prestashop/issues/41
