### ISSUE TITLE
54-ФЗ Купон на скидку: не проходят платежи, ошибка кассы

### ISSUE THREAD

**Issue by Sovush** [yandex-money/yandex-money-cms-prestashop#41]
Связка с кассой Атол онлайн. Преста 1.6.1.4 Если использовать при заказе купон на скидку в процентах- все нормально. Если купон на скидку носит числовое значение- ошибка и платеж кассой не зачисляется. 
Лог Атол:
Ответ от ККТ: [-3863] Описание: Скидка/надбавка на предыдущую операцию невозможна

Комментарий Яндекса по ошибке:
В онлайн-кассу (Атол Онлайн, Модуль.Касса и т.д.) мы передаем ym_merchant_receipt и sum. Они проверяют их соответствие: что общая сумма чека из ym_merchant_receipt совпадает с суммой из sum. Оба этих значения должны быть равны.

В случае, если общая сумма ym_merchant_receipt не совпадет со значением из sum, платеж не будет фискализирован, платеж будет отменен нашей системой, плательщик получит деньги обратно, а на вашу электронную почту придет письмо об ошибке фискализаци

**Comment by Sovush** [comment]
В yamodule.php стр 531:

$disc = round(($params['order']->total_discounts_tax_incl * 100 /$params['order']->total_products_wt), 2);
            foreach ($products as $pk => &$product) {
                $product['unit_price_tax_incl'] = round($product['unit_price_tax_incl'] * $disc / 100, 2);

Такой код, вроде бы, срабатывает без ошибок. Но вопрос с купоном на бесплатную доставку открыт- его применение дает ошибку.

**Comment by ikarmanov** [comment]
Добрый день.

До 28.08.2017 выпустим новую версию модуля, которая будет нормализовать состав чека по сумме.
