### ISSUE TITLE
Attempted to load class "Blowfish" from the global namespace.

### ISSUE THREAD

**Issue by tsvetkovpro** [yandex-money/yandex-money-cms-prestashop#42]
доброго дня, устанавливаю модуль  ycms.prestashop.zip из этого репозитория и получается вкладка модули перестает работать. Как можно исправить ?

![image](https://user-images.githubusercontent.com/2004857/30239411-729ada92-9575-11e7-976e-6f9913cbc783.png)

**Comment by ven1aone** [comment]
Решена проблема?

**Comment by tersosufix** [comment]
Охренеть. Я теперь в модули не могу зайти вообще. Даже если выбираю отключить сторонние модули.

**Comment by DaoKakao** [comment]
Это проблема актуальна для версии 1.7 - там выпилили классы Blowfish и Rijndael, вместо них используется PhpEncryption. 
По идее фикс должен быть простым, но учитывать версию престы.

**Comment by ostulov** [comment]
Для Prestashop 1.7 необходимо использовать другой модуль - https://github.com/yandex-money/yandex-money-ycms-v2-prestashop
