### ISSUE TITLE
Order confirmation 404 error

### ISSUE THREAD

**Issue by Artunj** [yandex-money/yandex-money-cms-prestashop#48]
Hi, I am getting 404 not found page on order confirmation page by yandex money payment system. 

 

Please see attached image: https://image.ibb.co/mrjeaG/yandex_payment_404.jpg

 

here is link of order confirmation page: http://domain,com/order-confirmation&id_cart=126&id_module=76&id_order=&key=7c59f6423cbc87ac1b5aaf86a80e5aef

 

Please advice

**Comment by ostulov** [comment]
If the problem is relevant, please write to cms@yamoney.ru with details
