### ISSUE TITLE
    Заказы в Маркете

### ISSUE THREAD

**Issue by rusbolik** [yandex-money/yandex-money-cms-prestashop#49]
как ни кручу ни верчу, никак не проходит самопроверку маркета.
Лог выдает {"error":{"code":403,"message":"Token is invalid"},"errors":[{"code":"FORBIDDEN","message":"Token is invalid"}],"status":"ERROR"}
  через 30 минут после обновления токенов - заработал токен
теперь при самопроверке контрольным заказаом выдает ошибку 500 при попытке смены статуса и открытия заказа в админке

**Comment by ostulov** [comment]
Поддержка сервиса "Заказы в Маркете" прекращена.
