### ISSUE TITLE
Проблема при установке модуля

### ISSUE THREAD

**Issue by Aurons77** [yandex-money/yandex-money-cms-prestashop#51]
Загрузка прерывается на таком сообщении и в модули попасть можно потом только удалив этот

Ой... Загрузка прервалась.

Что случилось?
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by solotony** [comment]
the same prooblem

in debug mode: message is

> Attempted to load class "Blowfish" from the global namespace.
> Did you forget a "use" statement?

**Comment by roffua** [comment]
При попытке установить ошибка:
"Не удается корректно установить этот модуль(-и):
yamodule : 
    Не получается установить перезапись: Метод setRequestUri класса Dispatcher уже переопределён в модуле fsadvancedurl версии 2.1.1"
Версия Prestashop 1.6

**Comment by karopka** [comment]
Ошибка при попытке установить модуль:
Attempted to load class "Blowfish" from the global namespace.
Did you forget a "use" statement?

**Comment by Kvarmall** [comment]
Такая же беда

**Comment by ostulov** [comment]
Данный модуль не подходит для Prestashop 1.7. Вы можете использовать следующий модуль - https://github.com/yandex-money/yandex-money-ycms-v2-prestashop
При возникновении ошибок для получения оперативной помощи просьба писать на cms@yamoney.ru  с указанием подробностей.
