### ISSUE TITLE
Ошибка валюты

### ISSUE THREAD

**Issue by magadar** [yandex-money/yandex-money-cms-prestashop#52]
При выборе в магазине валюты отличной от рубля (доллар, евро), в яндекс кассу передаётся сумма в выбранной валюте но обозначенной как рубли.
Например: сумма заказа 5 доллара, в яндекс кассу передается сумма 5 рублей. Платёж не проходит выдаёт ошибку. После у этого заказа в админке сумма превращается в 340$ долларов (вместо 340 рублей).
Prestashop 1.6.1.18, модуль 1.4.6, основная валюта рубль

**Comment by ostulov** [comment]
Добрый день!

Валюта приема оплаты задается на стороне Яндекс.Кассы. Возможность принимать оплату в валюте устанавливается для каждого магазина отдельно. Вы можете уточнить о возможности принимать оплату не только в рублях у своего персонального менеджера.
