### ISSUE TITLE
Слетела Метрика после установки 1.4.7

### ISSUE THREAD

**Issue by rusbolik** [yandex-money/yandex-money-cms-prestashop#54]
Обновил модуль. 
Метрика перестала отслеживать цели.
Вошёл в модуль, вкладка Яндекс.Метрика - всё настроенно
На всякий случай жму "Сохранить" и получаю ответ 
```
Настройки успешно сохранены! 
Saving the settings the meter is not the meter number is incorrect.
```
Что значит номер не является номером? 
Всё стоит правильно
![screenshot_32](https://user-images.githubusercontent.com/25536873/38754800-dffa5464-3f6b-11e8-8bb0-91e07f81c153.jpg)

**Comment by ostulov** [comment]
Отслеживание целей в Метрике изменилось.
Для более подробного разбора проблемы напишите письмо на почту cms@yamoney.ru со скриншотами настроек.

**Comment by rusbolik** [comment]
Спасибо.
Написал. Буду ждать ответ
