### ISSUE TITLE
Yandex.Маркет

### ISSUE THREAD

**Issue by mrJohnNova** [yandex-money/yandex-money-cms-prestashop#8]
Не сохраняется параметр YA_MARKET_CATALL (Выгружать) во вкладке Yandex.Маркет. Скорее всего забыли в добавить его в validateMarket() в файле yamodule.php

**Comment by ikarmanov** [comment]
Добрый день.

Мы выпустили новую версию модуля. Ваша проблема еще актуальна?

**Comment by freedayko** [comment]
Добавьте, пожалуйста, выбор основной валюты для прайса, так как в случае когда основная валюта магазина доллар в прайсе, маркет его не принимает. Спасибо

**Comment by OnlyBelBy** [comment]
"freedayko commented on 5 Feb
Добавьте, пожалуйста, выбор основной валюты для прайса, так как в случае когда основная валюта магазина доллар в прайсе, маркет его не принимает. Спасибо"

Добрый день, присоединяюсь к данному вопросу .....
Когда появится возможность **выбора валюты** для выгрузки **цен** на товары в прайсе для я.маркета?  
В настройках модуля есть пункт -  "Выгружать все валюты? (Если нет, выгрузится только поумолчанию)", но при его активации выгружаются только все валюты используемые в магазине в виде простого кода , но цены на товар все равно выгружаются в ОСНОВНОЙ ВАЛЮТЕ магазина, т.е. в $, а я.маркет не принимает доллары в прайсе.
Очень огромная просьба поспособствовать в решении данной проблемы, либо подскажите где именно в коде происходит формирование цены на Товары (чтобы не перерывать все файлы в  его поисках...)
Заранее спасибо за ответ.

**Comment by magprofoto** [comment]
Как добавить   <sales_notes>предоплата</sales_notes>.
через модуль для prestoshop?
