### ISSUE TITLE
Yandex.Маркет Категории

### ISSUE THREAD

**Issue by mrJohnNova** [yandex-money/yandex-money-cms-prestashop#9]
На Prestashop 1.5.6.1 не работает вывод категории. Просто не выводит их.

Исправлено после изменения в строчке 229 в файле hforms.php на:

array(
    'type' => 'categories',
    'label' => $this->l('Категории'),
    'desc' => $this->l('Выберите категории для экспорта. Если нужны подкатегории, отметте их.'),
    'name' => 'YA_MARKET_CATEGORIES',
    'values' => array(
        'trads' => array(
                                'Root' => $root_category,
                                'selected' => $this->l('Selected'),
                                'Check all' => $this->l('Check all'),
                                'Check All' => $this->l('Check All'),
                                'Uncheck All'  => $this->l('Uncheck All'),
                                'Collapse All' => $this->l('Collapse All'),
                                'Expand All' => $this->l('Expand All'),
                            ),
        'use_search' => false,
        'use_checkbox' => true,
                'input_name' => 'categoryBox[]',
                'selected_cat' => $this->cats,
),
),

Добавил в начало функции:
$root_category = Category::getRootCategory();
$root_category = array('id_category' => $root_category->id, 'name' => $root_category->name);

Изменить строчку 1154 в файле yamodule.php на:
Configuration::UpdateValue('YA_MARKET_CATEGORIES', serialize(Tools::getValue('categoryBox')));

**Comment by ikarmanov** [comment]
Добрый день.

Спасибо за информацию. Проверим актуальность данного предложения.
